### ISSUE TITLE
Is This Still Secure/Up-To-Date?

### ISSUE THREAD

**Issue by zicklag** [habnabit/passacre#6]
Hey there! I found this project and think it is a great idea, but I see that it hasn't been updated in three years and I wanted to know if there would be any security concern to that or if it is still just as good to use now. :smiley:

**Comment by habnabit** [comment]
Very short answer: 

- I haven't had the energy to update most of the projects under my personal account in a long time, so development has stalled.
- I don't know if/when that might change, given that in the last year I've started to move things over to 1password instead. I might write up a 'lessons learned' type blog post about that.
- As far as I'm aware, there's nothing fundamentally insecure about the idea or the implementation. The only reason I've switched is personal convenience.
